apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: db:5432
    database: garmin
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      timescaledb: true
    isDefault: true
